<?php

namespace App\Http\Services;
        
use App\Models\Category;

class CategoryService extends Service
{
    public $model = Category::class;

    /* This is an example of a service generated by the command 'make:service Model' */
}